version: '3'

services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7000:7000"
    deploy:
      mode: replicated
      replicas: 1